areasDict = {
'Barking and Dagenham':[],
'Barnet':[],
'Bexley':[],
'Brent':[],
'Bromley' :[],
'Camden':[],
'Croydon':[],
'Ealing':[],
'Enfield':[],
'Greenwich':[],
'Hackney':[],
'Hammersmith and Fulham':[],
'Haringey':[],
'Harrow':[],
'Hillingdon':[],
'Havering':[],
'Hounslow':[],
'Islington':[],
'Kensington and Chelsea':[],
'Kingston-Upon-Thhames':[],
'Lambeth':[],
'Lewisham':[],
'London (City of)':[],
'Merton':[],
'Redbridge':[],
'Richmond-Upon-Thames':[],
'Southwark':[],
'Sutton':[],
'Tower Hamlets':[],
'Waltham Forest':[],
'Wandsworth':[],
'Westminster':[]
    }
